package com.example.workspace

import android.util.Log
import com.example.mcp.McpRuntimeManager
import com.example.mcp.ToolSchemaDsl.schema
import org.json.JSONObject

/**
 * Claude Code-style agent tool.
 *
 * Spawns a [SubAgent] with isolated context, executes it synchronously,
 * and returns the last assistant message as the tool result.
 *
 * Key design:
 * - SubAgent gets a fresh `messages = ArrayList()` (not shared with parent)
 * - SubAgent gets `disallowedTools = setOf("agent")` to prevent recursion
 * - SubAgent's `onToolCall` routes directly to [McpRuntimeManager.callTool]
 * - SubAgent's `onStreamChunk` is a no-op (streams not shown to user)
 * - Errors are caught and returned as result text (not thrown)
 */
class AgentTool(
    private val mcpRuntimeManager: McpRuntimeManager,
    private val onSubAgentCreated: (name: String, description: String) -> Unit = { _, _ -> },
    private val onSubAgentStreamChunk: (name: String, chunk: String) -> Unit = { _, _ -> },
    private val onSubAgentCompleted: (name: String, messages: List<AgentMessage>) -> Unit = { _, _ -> },
) {
    companion object {
        private const val TAG = "AgentTool"
        const val TOOL_NAME = "agent"

        /**
         * Tool schema in McpTool inputSchema format.
         *
         * Parameters:
         * - description (required): short description of what the SubAgent will do
         * - prompt (required): full task prompt for the SubAgent
         * - model (optional): override model ID for the SubAgent
         */
        val TOOL_SCHEMA = schema {
            prop("description", "string", "Short description of what the SubAgent will do.")
            prop("prompt", "string", "Full task prompt for the SubAgent.")
            prop("model", "string", "Optional model ID to override the SubAgent's model.")
            required("description", "prompt")
        }
    }

    /**
     * Execute the agent tool.
     *
     * Creates an isolated SubAgent context, runs it with the given prompt,
     * and returns the last assistant message as the result.
     *
     * @param args JSON arguments containing `description`, `prompt`, and optionally `model`
     * @param parentContext the calling agent's context (used to inherit model config)
     * @param sandboxPath optional sandbox path for file operations
     * @return a JSON object with `content` (string) and optionally `isError` (boolean)
     */
    suspend fun call(
        args: JSONObject,
        parentContext: AgentContext,
        sandboxPath: String,
    ): JSONObject {
        val description = args.optString("description", "")
        val prompt = args.optString("prompt", "")
        val modelOverride = args.optString("model", "").ifEmpty { null }

        if (prompt.isEmpty()) {
            return errorResult("Missing required parameter: prompt")
        }

        return try {
            runSubAgent(description, prompt, modelOverride, parentContext, sandboxPath)
        } catch (e: Exception) {
            Log.e(TAG, "SubAgent execution failed", e)
            errorResult("SubAgent execution failed: ${e.message}")
        }
    }

    /**
     * Create an isolated SubAgent context and run it.
     *
     * The SubAgent gets:
     * - A fresh message list (no shared state with parent)
     * - `disallowedTools = setOf("agent")` to prevent recursive agent spawning
     * - A system prompt generated by [buildSubAgentPrompt]
     * - The parent's model config (optionally overridden)
     */
    private suspend fun runSubAgent(
        description: String,
        prompt: String,
        modelOverride: String?,
        parentContext: AgentContext,
        sandboxPath: String,
    ): JSONObject {
        val subAgentName = "SubAgent-${java.util.UUID.randomUUID().toString().take(8)}"

        val subAgentContext = AgentContext(
            agentName = subAgentName,
            isOrchestrator = false,
            systemPrompt = buildSubAgentPrompt(description, sandboxPath),
            modelConfig = parentContext.modelConfig,
            overrideModelId = modelOverride,
            teamName = parentContext.teamName,
            messages = ArrayList(),
        )

        // Notify UI: SubAgent created
        onSubAgentCreated(subAgentName, description)

        val runner = AgentRunner(
            context = subAgentContext,
            mcpRuntimeManager = mcpRuntimeManager,
            disallowedTools = setOf(TOOL_NAME),
            sandboxPath = sandboxPath,
            onStreamChunk = { _, chunk ->
                // Forward stream chunks to UI for live display
                onSubAgentStreamChunk(subAgentName, chunk)
            },
            onToolCall = { _, toolName, toolArgs, _ ->
                val serverId = mcpRuntimeManager.findServerIdForTool(toolName)
                if (serverId == null) {
                    Log.e(TAG, "Tool '$toolName' not found in any MCP server")
                    "Error: Tool '$toolName' not found"
                } else {
                    val result = mcpRuntimeManager.callTool(serverId, toolName, toolArgs)
                    result?.toString() ?: "No result"
                }
            },
        )

        try {
            runner.runTurn(userMessage = prompt, source = "agent-tool")
        } finally {
            runner.dispose()
        }

        // Notify UI: SubAgent completed with its messages
        onSubAgentCompleted(subAgentName, subAgentContext.messages.toList())

        // Extract the last assistant message from the SubAgent's conversation
        val lastAssistantMsg = subAgentContext.messages
            .lastOrNull { it.role == "assistant" && it.content.isNotBlank() }

        val resultText = lastAssistantMsg?.content
            ?: "(SubAgent completed with no output)"

        return successResult(resultText)
    }

    /**
     * Generate an English system prompt for the SubAgent.
     */
    private fun buildSubAgentPrompt(description: String, sandboxPath: String): String {
        return buildString {
            appendLine("You are a focused sub-agent executing a specific task.")
            appendLine("Task: $description")
            appendLine()
            appendLine("Instructions:")
            appendLine("- Execute the task as described in the user prompt.")
            appendLine("- Use available tools to complete the work.")
            appendLine("- Report your findings clearly and concisely.")
            if (sandboxPath.isNotBlank()) {
                appendLine("- File operations are restricted to: $sandboxPath")
            }
        }
    }

    /**
     * Build a success result JSON object.
     */
    private fun successResult(content: String): JSONObject = JSONObject().apply {
        put("content", content)
    }

    /**
     * Build an error result JSON object.
     */
    private fun errorResult(message: String): JSONObject = JSONObject().apply {
        put("content", "Error: $message")
        put("isError", true)
    }
}
